package org.bitbucket.creditauto;

import static org.junit.Assert.assertTrue;
import static org.junit.Assert.assertEquals;

import org.junit.Test;
import org.junit.Ignore;

public class CreateDossierCar6Test extends AbstractWebDriverTest {
    @Ignore @Test public void createDossierCar6() throws Exception {
selenium.open("/creditauto");
boolean loginPresent = selenium.isElementPresent("id=login");
// selenium.gotoIf("${loginPresent}", "doLogin");
if (!loginPresent) {
selenium.click("link=Выйти из системы");
selenium.waitForPageToLoad("90000");
}
// selenium.label("doLogin");
assertTrue(selenium.isTextPresent("Вход в систему"));
selenium.type("//input[@name='username']", "demo");
selenium.type("//input[@name='password']", "demo");
selenium.type("id=logonForm:sap_bp_id", "00124");
selenium.click("id=login");
selenium.waitForPageToLoad("90000");
assertTrue(selenium.isTextPresent("ТОВ \"УкрАвтоХолдинг\""));
assertTrue(selenium.isTextPresent("Добро пожаловать, Demo User"));
assertTrue(selenium.isElementPresent("link=Создать заявку"));
selenium.click("link=Создать заявку");
selenium.waitForPageToLoad("90000");
selenium.select("partialId=in_goods.0.dictionary_carBrand", "label=Audi");
Thread.sleep(1000);
selenium.select("partialId=in_goods.0.dictionary_carModel", "label=A4");
selenium.type("partialId=in_goods.0.price", "120000");
selenium.type("partialId=in_dossier.down_payment_value", "30000");
selenium.select("partialId=in_dossier.down_payment_calc_method", "label=Сумма");
Thread.sleep(500);
selenium.click("id=next");
selenium.waitForPageToLoad("90000");
selenium.type("partialId=in_goods.0.car_body_number", "12345678901234567");
selenium.type("partialId=in_goods.0.car_issue_year", "2010");
selenium.type("partialId=in_goods.0.car_engine_volume", "1600");
selenium.click("partialId=in_goods.0.in_stock");
selenium.select("partialId=in_goods.0.dict_car_transmission_type", "label=автоматическая");
selenium.select("partialId=in_goods.0.dict_car_body_type", "label=Седан");
selenium.select("partialId=in_goods.0.dict_car_fuel_type", "label=Бензин");
selenium.type("partialId=in_goods.0.car_bundling_type", "Комплектация");
selenium.select("partialId=in_goods.0.dict_car_color", "label=Черный");
selenium.click("id=next");
selenium.waitForPageToLoad("90000");
assertTrue(selenium.isTextPresent("Выбор типа кредита"));
String downPayment = selenium.getValue("partialId=in_dossier.down_payment");
assertEquals("30000,00", selenium.getExpression(selenium.getEval("'" + downPayment + "'.replace(/\\D+/,'')")));
selenium.click("id=next");
selenium.waitForPageToLoad("90000");
assertEquals("- не выбрано - “Акція_12_15%” “Акція_24_15%” “Акція_36_15%”", selenium.getText("partialId=in_dossier.credittype_id"));
selenium.select("partialId=in_dossier.credittype_id", "label=“Акція_24_15%”");
Thread.sleep(500);
selenium.click("id=next");
selenium.waitForPageToLoad("90000");
assertTrue(selenium.isTextPresent("Персональные данные клиента"));
selenium.select("partialId=in_person.dictionary_gender", "label=Мужской");
selenium.type("partialId=in_person.last_name", "Фамилия123");
selenium.type("partialId=in_person.first_name", "Имя123");
selenium.type("partialId=in_person.patronymic_name", "Отчество345");
selenium.type("partialId=in_person.birthday", "01011980");
selenium.type("partialId=in_person.birth_place", "Место рождения12");
selenium.type("partialId=in_person.tin", "2345678901");
selenium.type("partialId=in_person.date_of_register_tin_certificate", "01011996");
selenium.type("partialId=in_person.date_of_issue_tin_certificate", "01011997");
selenium.type("partialId=in_person.issuer_of_tin", "Кем выдан ИНН 12");
selenium.type("partialId=in_person.identity_document_number", "ОО3456789");
selenium.type("partialId=in_person.date_of_issuing_identity_doc", "01011998");
selenium.type("partialId=in_person.issuer_of_identity_document", "Кем выдан паспорт 56");
selenium.click("id=next");
selenium.waitForPageToLoad("90000");
assertEquals("Неверный формат данных", selenium.getTable("css=table.1.1"));
assertEquals("Неверный формат данных", selenium.getTable("css=table.2.1"));
assertEquals("Неверный формат данных", selenium.getTable("css=table.3.1"));
assertEquals("Неверный формат данных", selenium.getTable("css=table.5.1"));
assertEquals("Не совпадает контрольная сумма для ИНН", selenium.getTable("css=table.6.1"));
assertEquals("Неверный формат данных", selenium.getTable("css=table.9.1"));
assertEquals("Неверный формат данных", selenium.getTable("css=table.10.1"));
assertEquals("Неверный формат данных", selenium.getTable("css=table.12.1"));
selenium.type("partialId=in_person.last_name", "Фамилия");
selenium.type("partialId=in_person.first_name", "Имя");
selenium.type("partialId=in_person.patronymic_name", "Отчество");
selenium.type("partialId=in_person.birth_place", "Место рождения");
selenium.type("partialId=in_person.tin", "2345678902");
selenium.type("partialId=in_person.issuer_of_tin", "Кем выдан ИНН");
selenium.type("partialId=in_person.identity_document_number", "ОО345678");
selenium.type("partialId=in_person.issuer_of_identity_document", "Кем выдан паспорт");
selenium.click("id=next");
selenium.waitForPageToLoad("90000");
selenium.select("partialId=in_person.dictionary_marital_status", "label=гражданский брак");
selenium.select("partialId=in_person.dictionary_habitation_situation", "label=Владелец недвижимости");
selenium.type("partialId=in_person.number_of_children", "2");
selenium.type("partialId=in_person.habit_situation_start_date", "01012009");
selenium.click("id=next");
selenium.waitForPageToLoad("90000");
selenium.select("partialId=in_person.dictionary_regprovince", "label=Київська");
Thread.sleep(1000);
selenium.select("partialId=in_person.dictionary_regregion", "label=Києво-Святошинський");
Thread.sleep(500);
selenium.select("partialId=in_person.dictionary_regcity", "label=Гатне");
Thread.sleep(500);
selenium.type("partialId=in_person.regstreet", "Улица");
selenium.type("partialId=in_person.reghouse", "12");
selenium.type("partialId=in_person.regflat", "23");
selenium.select("partialId=in_person.dictionary_mailprovince", "label=Вінницька");
Thread.sleep(500);
selenium.select("partialId=in_person.dictionary_mailregion", "label=Гайсинський");
Thread.sleep(500);
selenium.select("partialId=in_person.dictionary_mailcity", "label=Гайсин 1");
Thread.sleep(500);
selenium.type("partialId=in_person.mailstreet", "Улица 2");
selenium.type("partialId=in_person.mailhouse", "45");
selenium.type("partialId=in_person.mailflat", "56");
selenium.click("id=next");
selenium.waitForPageToLoad("90000");
selenium.click("link=Выйти из системы");
selenium.waitForPageToLoad("90000");
assertTrue(selenium.isTextPresent("Вход в систему"));
    }
}
