package org.bitbucket.creditauto;

import java.util.regex.*;

import static org.junit.Assert.assertTrue;
import static org.junit.Assert.assertEquals;

import org.junit.Test;
import org.junit.Ignore;

public class CreateDossierCar2Test extends AbstractWebDriverTest {
    @Ignore @Test public void createDossierCar2() throws Exception {
selenium.open("/creditauto");
boolean loginPresent = selenium.isElementPresent("id=login");
// selenium.gotoIf("${loginPresent}", "doLogin");
if (!loginPresent) {
selenium.click("link=Выйти из системы");
selenium.waitForPageToLoad("90000");
}
// selenium.label("doLogin");
assertTrue(selenium.isTextPresent("Вход в систему"));
selenium.type("//input[@name='username']", "demo");
selenium.type("//input[@name='password']", "demo");
selenium.type("id=logonForm:sap_bp_id", "00123");
selenium.click("id=login");
selenium.waitForPageToLoad("90000");
assertTrue(selenium.isTextPresent("Добро пожаловать, Demo User"));
assertTrue(selenium.isElementPresent("link=Создать заявку"));
selenium.click("link=Создать заявку");
selenium.waitForPageToLoad("90000");
selenium.select("partialId=in_goods.0.dictionary_carBrand", "label=Audi");
Thread.sleep(500);
selenium.select("partialId=in_goods.0.dictionary_carModel", "label=A4");
Thread.sleep(500);
selenium.type("partialId=in_goods.0.price", "120000");
selenium.type("partialId=in_dossier.down_payment_value", "40");
selenium.select("partialId=in_dossier.down_payment_calc_method", "label=Процент");
Thread.sleep(500);
selenium.click("id=next");
selenium.waitForPageToLoad("90000");
selenium.type("partialId=in_goods.0.car_body_number", "12345678901234567");
selenium.type("partialId=in_goods.0.car_issue_year", "2010");
selenium.type("partialId=in_goods.0.car_engine_volume", "1600");
selenium.click("partialId=in_goods.0.in_stock");
selenium.select("partialId=in_goods.0.dict_car_transmission_type", "label=автоматическая");
selenium.select("partialId=in_goods.0.dict_car_body_type", "label=Седан");
selenium.select("partialId=in_goods.0.dict_car_fuel_type", "label=Бензин");
selenium.type("partialId=in_goods.0.car_bundling_type", "Комплектация");
selenium.select("partialId=in_goods.0.dict_car_color", "label=Черный");
selenium.click("id=next");
selenium.waitForPageToLoad("90000");
assertTrue(selenium.isTextPresent("Выбор типа кредита"));
String downPayment = selenium.getValue("partialId=in_dossier.down_payment");
assertEquals("48000,00", selenium.getExpression(selenium.getEval("'" + downPayment + "'.replace(/\\D+/,'')")));
selenium.click("id=next");
selenium.waitForPageToLoad("90000");
selenium.select("partialId=in_dossier.credittype_id", "label=“Акція_24_15%”");
Thread.sleep(500);
selenium.click("id=next");
selenium.waitForPageToLoad("90000");
assertTrue(selenium.isTextPresent("Персональные данные клиента"));
selenium.select("partialId=in_person.dictionary_gender", "label=Мужской");
selenium.type("partialId=in_person.last_name", "Фамилия");
selenium.type("partialId=in_person.first_name", "Имя");
selenium.type("partialId=in_person.patronymic_name", "Отчество");
selenium.type("partialId=in_person.birthday", "01011980");
selenium.type("partialId=in_person.birth_place", "Место рождения");
selenium.type("partialId=in_person.tin", "2345678902");
selenium.type("partialId=in_person.date_of_register_tin_certificate", "01011996");
selenium.type("partialId=in_person.date_of_issue_tin_certificate", "01011997");
selenium.type("partialId=in_person.issuer_of_tin", "Кем выдан ИНН");
selenium.type("partialId=in_person.identity_document_number", "ОО345678");
selenium.type("partialId=in_person.date_of_issuing_identity_doc", "01011998");
selenium.type("partialId=in_person.issuer_of_identity_document", "Кем выдан паспорт");
selenium.click("id=next");
selenium.waitForPageToLoad("90000");
selenium.select("partialId=in_person.dictionary_marital_status", "label=regexp:Женат\\s/\\sзамужем");
selenium.select("partialId=in_person.dictionary_habitation_situation", "label=regexp:Владелец\\sнедвижимости\\sвыплачивает\\sкредит");
selenium.type("partialId=in_person.number_of_children", "2");
selenium.type("partialId=in_person.habit_situation_start_date", "01012009");
selenium.click("id=next");
selenium.waitForPageToLoad("90000");
selenium.select("partialId=in_person.dictionary_regprovince", "label=Київська");
Thread.sleep(500);
selenium.select("partialId=in_person.dictionary_regregion", "label=Києво-Святошинський");
Thread.sleep(500);
selenium.select("partialId=in_person.dictionary_regcity", "label=Гатне");
Thread.sleep(500);
selenium.type("partialId=in_person.regstreet", "Улица");
selenium.type("partialId=in_person.reghouse", "12");
selenium.type("partialId=in_person.regflat", "23");
selenium.select("partialId=in_person.dictionary_mailprovince", "label=Вінницька");
Thread.sleep(500);
selenium.select("partialId=in_person.dictionary_mailregion", "label=Гайсинський");
Thread.sleep(500);
selenium.select("partialId=in_person.dictionary_mailcity", "label=Гайсин 1");
Thread.sleep(500);
selenium.type("partialId=in_person.mailstreet", "Улица 2");
selenium.type("partialId=in_person.mailhouse", "45");
selenium.type("partialId=in_person.mailflat", "56");
selenium.click("id=next");
selenium.waitForPageToLoad("90000");
selenium.click("link=Создать заявку");
selenium.waitForPageToLoad("90000");
assertEquals("Audi", selenium.getSelectedLabel("partialId=in_goods.0.dictionary_carBrand"));
assertEquals("A4", selenium.getSelectedLabel("partialId=in_goods.0.dictionary_carModel"));
//assertTrue(Pattern.compile("120\\s000,00").matcher(selenium.getValue("partialId=in_goods.0.price")).find());
assertEquals("40,00", selenium.getValue("partialId=in_dossier.down_payment_value"));
assertEquals("Процент", selenium.getSelectedLabel("partialId=in_dossier.down_payment_calc_method"));
selenium.click("id=next");
selenium.waitForPageToLoad("90000");
assertEquals("12345678901234567", selenium.getValue("partialId=in_goods.0.car_body_number"));
assertEquals("2010", selenium.getValue("partialId=in_goods.0.car_issue_year"));
assertEquals("1600", selenium.getValue("partialId=in_goods.0.car_engine_volume"));
assertEquals("on", selenium.getValue("partialId=in_goods.0.in_stock"));
selenium.click("id=next");
selenium.waitForPageToLoad("90000");
assertEquals("“Акція_24_15%”", selenium.getSelectedLabel("partialId=in_dossier.credittype"));
assertTrue(selenium.isTextPresent("Выбор типа кредита"));
selenium.click("id=next");
selenium.waitForPageToLoad("90000");
assertEquals("Мужской", selenium.getSelectedLabel("partialId=in_person.dictionary_gender"));
assertEquals("Фамилия", selenium.getValue("partialId=in_person.last_name"));
assertEquals("Имя", selenium.getValue("partialId=in_person.first_name"));
assertEquals("Отчество", selenium.getValue("partialId=in_person.patronymic_name"));
assertEquals("01011980", selenium.getValue("partialId=in_person.birthday"));
assertEquals("Место рождения", selenium.getValue("partialId=in_person.birth_place"));
assertEquals("2345678902", selenium.getValue("partialId=in_person.tin"));
assertEquals("01011996", selenium.getValue("partialId=in_person.date_of_register_tin_certificate"));
assertEquals("01011997", selenium.getValue("partialId=in_person.date_of_issue_tin_certificate"));
assertEquals("Кем выдан ИНН", selenium.getValue("partialId=in_person.issuer_of_tin"));
assertEquals("ОО345678", selenium.getValue("partialId=in_person.identity_document_number"));
assertEquals("01011998", selenium.getValue("partialId=in_person.date_of_issuing_identity_doc"));
assertEquals("Кем выдан паспорт", selenium.getValue("partialId=in_person.issuer_of_identity_document"));
selenium.click("id=next");
selenium.waitForPageToLoad("90000");
assertTrue(Pattern.compile("Женат\\s/\\sзамужем").matcher(selenium.getSelectedLabel("partialId=in_person.dictionary_marital_status")).find());
assertEquals("2", selenium.getValue("partialId=in_person.number_of_children"));
assertEquals("Владелец недвижимости выплачивает кредит", selenium.getSelectedLabel("partialId=in_person.dictionary_habitation_situation"));
assertEquals("01012009", selenium.getValue("partialId=in_person.habit_situation_start_date"));
assertTrue(selenium.isTextPresent("Семейное положение:"));
selenium.click("id=next");
selenium.waitForPageToLoad("90000");
assertTrue(selenium.isTextPresent("Заполнение адреса клиента"));
assertEquals("Київська", selenium.getSelectedLabel("partialId=in_person.dictionary_regprovince"));
assertEquals("Києво-Святошинський", selenium.getSelectedLabel("partialId=in_person.dictionary_regregion"));
assertEquals("Гатне", selenium.getSelectedLabel("partialId=in_person.dictionary_regcity"));
assertEquals("Улица", selenium.getValue("partialId=in_person.regstreet"));
assertEquals("", selenium.getValue("partialId=in_person.regadditionalinfo"));
assertEquals("12", selenium.getValue("partialId=in_person.reghouse"));
assertEquals("23", selenium.getValue("partialId=in_person.regflat"));
assertTrue(selenium.isElementPresent("partialId=in_person.dictionary_mailprovince"));
assertTrue(selenium.isElementPresent("partialId=in_person.dictionary_mailregion"));
assertTrue(selenium.isElementPresent("partialId=in_person.dictionary_mailcity"));
assertEquals("Улица 2", selenium.getValue("partialId=in_person.mailstreet"));
assertEquals("45", selenium.getValue("partialId=in_person.mailhouse"));
assertEquals("56", selenium.getValue("partialId=in_person.mailflat"));
assertEquals("", selenium.getValue("partialId=in_person.mailadditionalinfo"));
selenium.click("id=next");
selenium.waitForPageToLoad("90000");
selenium.click("link=Выйти из системы");
selenium.waitForPageToLoad("90000");
assertTrue(selenium.isTextPresent("Вход в систему"));
    }
}
